유저 컨트롤러 테스트 작성 중
shoppingmall-page-study/Shoppingmall_Project_BackEnd pull request #159
Opened 2023-03-20 06:10 UTC by Dongbok-Lee

레디스는 테스트하기 애매해서 일단 뺌
UserService
UserRepository

2023-03-20 07:10 UTC, Dongbok-Lee commented
https://topaz-joke-66e.notion.site/53a7f00336744be0975293a1fe5d2d7d
관련자료

2023-03-22 06:53 UTC, limjongheok requested changes

2023-03-22 06:53 UTC, limjongheok commented on src/test/java/com/project/shopping/service/UserServiceTest.java
> +                .roles("ROLE_USER")
ROLE_GUEST 변경 요청

2023-03-22 06:53 UTC, limjongheok commented on src/test/java/com/project/shopping/service/UserServiceTest.java
> +    public void saveUser () throws Exception{
삭제후 oauthUserInfoAdd 메서드 테스트 요망

2023-03-22 06:53 UTC, limjongheok commented on src/test/java/com/project/shopping/controller/UserControllerTest.java
> +    @DisplayName("## OAuth 회원가입 ##")
OAuth 변경에 따른 삭제 후 "/api/oauth/user/info/add" 로 변경요망

2023-03-22 06:53 UTC, limjongheok commented on src/test/java/com/project/shopping/controller/UserControllerTest.java
> +}
일반 로그인 "/api/login" 추가 요청

2023-03-23 02:43 UTC, Dongbok-Lee commented on src/test/java/com/project/shopping/controller/UserControllerTest.java
> +}
시큐리티 관련은 나중에 처리예정

2023-03-27 06:41 UTC, merged